### ISSUE TITLE
StartPos Label Object summary button

### ISSUE THREAD

**Issue by NonCloud9** [Alphalaneous/Object-Summary#1]
You know, having the object counter button on the StartPos menu can be a little dangerous cause someone can press it accidentaly and if don't save the level it can be punish.

Hope you fix.

https://github.com/user-attachments/assets/9477dc35-921a-48a6-802c-b7cc79af1d79

//
[2024-08-16_17-30-54.txt](https://github.com/user-attachments/files/16642378/2024-08-16_17-30-54.txt)
[2024-08-16_17-36-11.txt](https://github.com/user-attachments/files/16642379/2024-08-16_17-36-11.txt)

**Comment by Alphalaneous** [comment]
Yeah that is unintentional, will fix when I get the chance, darn GD and using the same popup for the level settings and start pos

**Comment by Alphalaneous** [comment]
Fixed

**Comment by NonCloud9** [comment]
Thanks, you think Rob wanted to work faster making the same popup for the startpos?
